### ISSUE TITLE
enable Django admin panel

### ISSUE THREAD

**Issue by mihai-sysbio** [elixir-europe-training/Training-Metrics-Database#21]
**Is your feature request related to a problem? Please describe.**
There is no way for a non-developer admin to manage user accounts.

**Describe the solution you'd like**
As an admin, I want to manage users from an interface, so that it's easier than the command-line way of doing it.

**Describe alternatives you've considered**

**Additional context**
The Django admin panel has been disabled.
This feature is related to https://github.com/elixir-europe-training/ELIXIR-TrP-Training-Metrics-Database-Tango/issues/13

**Comment by unode** [comment]
To be further investigated:
- Can [Django SAML 2](https://github.com/IdentityPython/djangosaml2) and [LS AAI](https://lifescience-ri.eu/ls-login/relying-parties/how-to-register-and-integrate-a-relying-party-to-ls-login.html) be used for admin panel authentication?

**Comment by ninanorgren** [comment]
Django panel enabled now, with user permissions, see issue #67 LS AAi is also discussed in issue #13 so I'm closing this for now.
