### ISSUE TITLE
Upload of new data into the TMD

### ISSUE THREAD

**Issue by ninanorgren** [elixir-europe-training/Training-Metrics-Database#36]
**Describe the solution you'd like**
As a training coordinator I would like to be able to upload my training metrics from csv into the TMD. I should be able to upload several courses at the same time.

**Describe alternatives you've considered**
Instead of using a form for adding course information metrics, we upload everything using a csv file. We provide a template csv that the coordinators can use to fill in their data, and then upload to the TMD. There will be one csv per metric, but they can be added to the same upload, and the system will handle them accordingly. If an update is needed, new files can be uploaded, and will then replace the existing entries in the database for those courses.

If possible and reasonable we want to follow the structure of the old bulk upload. The data sets that should be possible to import (as described by the old TMD):
- Events: [Events_template.csv](https://github.com/elixir-europe-training/Training-Metrics-Database/files/14837784/Events_template.csv)
- Quality and demographic metrics: [Demographic_Quality_metrics_template.csv](https://github.com/elixir-europe-training/Training-Metrics-Database/files/14837787/Demographic_Quality_metrics_template.csv)
- Impact metrics: [impact_metrics_template.csv](https://github.com/elixir-europe-training/Training-Metrics-Database/files/14837785/impact_metrics_template.csv)

**Comment by ninanorgren** [comment]
Instructions for how the input csv should be formatted should be on the old TMD page

**Comment by pdmnyberg** [comment]
Link to how-to: https://training-metrics-dev.elixir-europe.org/how-to-guide

**Comment by pdmnyberg** [comment]
I think this issue has been addressed. Further work should be detailed in other issues as bugs or new features.
