### ISSUE TITLE
Bulk upload: make sure accepted values fit with the specifications

### ISSUE THREAD

**Issue by olisand** [elixir-europe-training/Training-Metrics-Database#42]
When I tried to upload bulk impact metrics, I got this error:
Failed to import ‘impact_metrics’: {‘main_attend_reason’: [“Value ‘To build on existing knowledge to aid me in my current research/ work’ is not a valid choice.“]}
But in the specifications (https://training-metrics-dev.elixir-europe.org/references?title=&field_reference_type_value=Impact+metrics), it is well one of the accepted values.
When that value is modified to "To build on existing knowledge to aid me in my current research/work’ is not a valid choice." (space removed between "/" and "work"), the upload works.
So there is a discrepancy between the accepted value and the specifications, at least in this case.

**Comment by ninanorgren** [comment]
Closed as irrelevant with new db model, see issue #49
