### ISSUE TITLE
Import events from TeSS

### ISSUE THREAD

**Issue by ninanorgren** [elixir-europe-training/Training-Metrics-Database#47]
As a **Training Coordinator** I want to be able to **import my course into the TMD directly from TeSS**, so that I don’t have to add all the information again.

**Comment by pdmnyberg** [comment]
For future reference. This is how you fetch event info from TeSS using an event url and the undocumented endpoint:
```
curl -v -X POST -H "Content-Type: application/json" https://tess.elixir-europe.org/materials/check_exists.json -d"{\"material\": {\"url\":\"https://elixirestonia.github.io/2024-10-23-shell-novice/setup.html\"}}"
```

**Comment by ninanorgren** [comment]
PR #75 fixes this now
