### ISSUE TITLE
TMD Database remodelling

### ISSUE THREAD

**Issue by eleni-adamidi** [elixir-europe-training/Training-Metrics-Database#49]
Support dynamic import of questions

## The model should
- Allow for a dynamic set of questions
- Clearly identify which questions are required for the shared TMD metrics collection
- Have human friendly ids for questions and answers in order to allow for a stable import systems (These ids should preferably be simplified rather than for ex. the entire question formulation)
  - Human friendly ids are easier to manage when working with data files such as CSV and when verifying implementations of automatic data transforms
  - Human friendly ids should make it harder to accidentally include hard to notice mistakes such as varying casing or additional white spaces

## The model may
- Include question and answer translations in order to import and export the metrics in a localized way
- Allow for the creation of sets of questions. Where an example set would be the "Common TMD Metrics"
- Allow for the creation of set groups in order to combine sets of questions (For ex. the "Common TMD Metrics" and "Additional SE Node Metrics" -> "Complete SE Node Metrics")

## The initial question dataset should
- Include at least the questions from the specification: https://training-metrics-dev.elixir-europe.org/references?title=&field_reference_type_value=Impact+metrics as detailed in the issue  #42
- Be identical to the reference in order to maintain backwards compatibility.
- Include predetermined human friendly ids for questions and answers

**Comment by pdmnyberg** [comment]
Given this specification I think what we have in the wip-branch more or less covers this. I will make sure to get it merged to develop and then I will close this issue.

We still need to create issues for the following:
- Improve Admin UI experience
  - Filtering
  - Improved granularity for auth
- Create a migration path from the old model to the new model
- Make the report pages compatible with the new model
- Make the upload compatible with the new model

**Comment by pdmnyberg** [comment]
The model is more or less stable and can be used. Continued work will be done here: https://github.com/elixir-europe-training/Training-Metrics-Database/issues/73
