### ISSUE TITLE
Link to TeSS

### ISSUE THREAD

**Issue by olisand** [elixir-europe-training/Training-Metrics-Database#6]
As a Training Coordinator, I want Tango to link to TeSS, so that I can import my events from TeSS instead of manual form-filling or bulk upload.
The link with the event in Tango and TeSS should be done by using a unique (TeSS?) ID.

**Comment by mihai-sysbio** [comment]
In the TMD the URL is a required field. In Bioschemas there is an ID field, and quite often this is the same as the URL. TeSS already has an API to get event details based on this user-provided ID.  All the components seem in place to make the connection.

**Comment by ninanorgren** [comment]
User story in biohackathon 2024, see #47

**Comment by ninanorgren** [comment]
Fixed by PR #75
